{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","msg","name","exception","isApplicationException","err","Object","getPrototypeOf","getExceptionMessage","message","console","log"],"mappings":";;;;;;gBAAaA,oB,GAAN,MAAMA,oBAAN,SAAmCC,KAAnC,CAAyC;;AAE5CC,4BAAYC,MAAM,EAAlB,EAAsB;;AAElB,0BAAMA,GAAN;AACA,yBAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACH;AAN2C,a;;;;AAShD,kBAAMC,YAAYL,oBAAlB;;AAEO,qBAASM,sBAAT,CAAgCC,GAAhC,EAAqC;;AAExC,uBAAOA,eAAeF,SAAf,IAA4BG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SAAzE;AACH;;;;AAEM,qBAASK,mBAAT,CAA6BH,GAA7B,EAAkC;;AAErC,oBAAGD,uBAAuBC,GAAvB,CAAH,EAAgC;AAC5B,2BAAOA,IAAII,OAAX;AACH,iBAFD,MAEO;AACHC,4BAAQC,GAAR,CAAYN,GAAZ;AACA,2BAAO,uCAAP;AACH;AACJ","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error {\r\n\r\n    constructor(msg = '') {\r\n\r\n        super(msg);\r\n        this.name = this.constructor.name;\r\n    }\r\n} \r\n\r\nconst exception = ApplicationException;\r\n\r\nexport function isApplicationException(err) {\r\n\r\n    return err instanceof exception || Object.getPrototypeOf(err) instanceof exception \r\n}\r\n\r\nexport function getExceptionMessage(err) {\r\n    \r\n    if(isApplicationException(err)) {\r\n        return err.message;\r\n    } else {\r\n        console.log(err);\r\n        return 'Não foi possível realizar a operação.';\r\n    }\r\n}"]}